version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: "ockovani"
      POSTGRES_USER: "ockovani"
      POSTGRES_DB: "ockovani"
  app:
    build:
      context: .
      dockerfile: dockerize/Dockerfile
    links:
      - db:db
    depends_on:
      - db
    environment:
      FLASK_ENV: "development"
      FETCH_DATA: "$FETCH_DATA"
    ports:
      - "5000:5000"

volumes:
  db_data: {}
